blank_issues_enabled: false

contact_links:
  - name: General Inquiries (non-technical)
    url: https://www.softworx.at/contact/
    about: Use this form for business, cooperation, or non-technical inquiries.
