blank_issues_enabled: false

contact_links:
  - name: Bug Reports
    url: https://github.com/andreas-schwab-swx/dd_image/issues/new?template=bug_report.md
    about: Report a reproducible problem in dd_image.

  - name: Feature Requests
    url: https://github.com/andreas-schwab-swx/dd_image/issues/new?template=feature_request.md
    about: Suggest an idea or enhancement for dd_image.

  - name: Support Questions
    url: https://github.com/andreas-schwab-swx/dd_image/issues/new?template=support_question.md
    about: Ask a question about usage, setup, or configuration.

  - name: General Inquiries (non-technical)
    url: https://www.softworx.at/contact/
    about: Use this form for business, cooperation, or non-technical inquiries.
