name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo mkdir -p /opt/scripts
          cd /opt/scripts/dd_image || git clone https://github.com/andreas-schwab-swx/dd_image.git /opt/scripts/dd_image
          cd /opt/scripts/dd_image
          git pull origin main
          sudo cp dd_image.sh /usr/local/sbin/
          sudo chmod +x /usr/local/sbin/dd_image.sh
          sudo chown root:root /usr/local/sbin/dd_image.sh